"""add_imagen_to_pilotos_and_confirmaciones

Revision ID: 2498313353ec
Revises: add_pasajeros
Create Date: 2025-10-17 12:02:11.901961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2498313353ec'
down_revision = 'add_pasajeros'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pilotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))

    with op.batch_alter_table('Confirmaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Confirmaciones', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('Pilotos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
