"""Add tipo_licencia and nacionalidad to Pilotos table

Revision ID: 4d2d59090924
Revises: 7a8b9c0d1e2f
Create Date: 2025-10-03 19:14:59.429736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2d59090924'
down_revision = '7a8b9c0d1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pilotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_licencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pilotos', schema=None) as batch_op:
        batch_op.drop_column('nacionalidad')
        batch_op.drop_column('tipo_licencia')

    # ### end Alembic commands ###
