"""Initial migration with relationships

Revision ID: d08f6bbd878e
Revises: 
Create Date: 2025-10-02 01:14:34.757416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08f6bbd878e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aeronaves',
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('tipo_aeronave', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('aeronave_id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('Pilotos',
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('licencia', sa.String(length=20), nullable=False),
    sa.Column('horas_vuelo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('piloto_id'),
    sa.UniqueConstraint('licencia')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('configuracion_aeropuerto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iata', sa.String(length=3), nullable=True),
    sa.Column('codigo_icao', sa.String(length=4), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sitio_web', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vuelos',
    sa.Column('vuelo_id', sa.Integer(), nullable=False),
    sa.Column('numero_vuelo', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('fecha_llegada', sa.DateTime(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('copiloto_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['Aeronaves.aeronave_id'], ),
    sa.ForeignKeyConstraint(['copiloto_id'], ['Pilotos.piloto_id'], ),
    sa.ForeignKeyConstraint(['piloto_id'], ['Pilotos.piloto_id'], ),
    sa.PrimaryKeyConstraint('vuelo_id'),
    sa.UniqueConstraint('numero_vuelo')
    )
    op.create_table('Confirmaciones',
    sa.Column('confirmacion_id', sa.Integer(), nullable=False),
    sa.Column('vuelo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vuelo_id'], ['Vuelos.vuelo_id'], ),
    sa.PrimaryKeyConstraint('confirmacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Confirmaciones')
    op.drop_table('Vuelos')
    op.drop_table('configuracion_aeropuerto')
    op.drop_table('Usuarios')
    op.drop_table('Pilotos')
    op.drop_table('Aeronaves')
    # ### end Alembic commands ###
